version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-builder
    container_name: crm-frontend-builder
    working_dir: /app/frontend
    command: sh -c "npm run build"
    volumes:
      - ./frontend:/app/frontend
    # env_file:
    #   - .env
